# Generated by Django 4.1.1 on 2022-10-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_news_deleted'),
    ]

    operations = [
    ]
