# Generated by Django 4.1.2 on 2022-11-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_courses_image_path_coursefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preambula',
        ),
        migrations.AddField(
            model_name='news',
            name='preambule',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Preambule'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.courses'),
        ),
    ]
